[package]
name = "spiceproject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
reqwest = "0.12.3"
serde_json = "1.0.115"
spiceai = "1.0.3"
tokio = "1.37.0"
